"""
Assembles the vw_bh_output view definition used by
data/borrower_history_validation_queries.sql's GATE 1 final-output checks,
from the checked-in data/borrower_history.txt -- so validation always runs
against the exact production query, not a manually pasted (and potentially
stale or hand-edited) copy.

Stamps the git commit SHA of data/borrower_history.txt into the output as a
comment, and warns if the working tree has uncommitted changes to it -- both
so the SHA can be recorded in GATE 6 as evidence of exactly what was
validated.

Usage:
    python scripts/build_vw_bh_output.py <validation_schema> > vw_bh_output.sql
    # then run vw_bh_output.sql in Athena/Trino
"""

import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "data" / "borrower_history.txt"

# Athena/Trino unquoted identifier: letters/digits/underscore, not starting
# with a digit. schema is interpolated directly into `CREATE OR REPLACE VIEW
# {schema}.vw_bh_output AS` below -- reject anything else rather than emit
# malformed or unintended SQL from a typo'd or pasted-wrong argument.
_VALID_SCHEMA = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# Matches the three literals in borrower_history.txt's `snapshots` CTE, e.g.
#   cast(20260531 AS bigint) AS snapshot_dt,
#   cast('2026-06-01 00:00:00.000' AS timestamp) AS as_of_load_ts,
#   cast('2026-06-01 00:00:00.000' AS timestamp) AS snapshot_ts
_SNAPSHOT_PARAM = re.compile(
    r"cast\(\s*('[^']*'|\d+)\s+AS\s+\w+\s*\)\s+AS\s+(snapshot_dt|as_of_load_ts|snapshot_ts)\b",
    re.IGNORECASE,
)


def _git(*args: str) -> str:
    try:
        return subprocess.run(
            ["git", "-C", str(REPO_ROOT), *args],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(f"Usage: python {Path(__file__).name} <validation_schema>")
    schema = sys.argv[1]
    if not _VALID_SCHEMA.match(schema):
        sys.exit(
            f"ERROR: '{schema}' is not a valid unquoted SQL identifier "
            "(letters/digits/underscore, not starting with a digit). "
            "Refusing to interpolate it into a CREATE VIEW statement."
        )

    if not SRC.exists():
        sys.exit(f"ERROR: {SRC} not found")

    sha = _git("log", "-1", "--format=%H", "--", "data/borrower_history.txt") or "unknown"
    dirty = bool(_git("status", "--porcelain", "--", "data/borrower_history.txt"))
    dirty_note = " -- WORKING TREE HAS UNCOMMITTED CHANGES TO THIS FILE, SHA ABOVE IS STALE" if dirty else ""

    body = SRC.read_text()

    # Extract the literal snapshot_dt/as_of_load_ts/snapshot_ts baked into
    # THIS file, so whoever runs the validation queries copies the exact
    # values instead of retyping them from memory or a stale note -- the
    # generated vw_bh_output and the hand-run validation queries silently
    # drifting onto different cutoffs would invalidate every reconciliation
    # result without necessarily looking wrong.
    # findall with two groups returns (value, name) tuples in match order;
    # key by name for lookup regardless of source ordering.
    params = {name: value for value, name in _SNAPSHOT_PARAM.findall(body)}

    print("-- Auto-generated by scripts/build_vw_bh_output.py -- DO NOT EDIT BY HAND.")
    print(f"-- Built from data/borrower_history.txt @ commit {sha}{dirty_note}")
    print("-- Record this commit SHA in GATE 6 of borrower_history_validation_queries.sql.")
    print("--")
    print("-- Use these EXACT values for :snapshot_dt / :as_of_load_ts / :snapshot_ts")
    print("-- when running borrower_history_validation_queries.sql -- if they don't match")
    print("-- what you substitute there, GATE 0's views and this production view are")
    print("-- validating two different cutoffs without any error being raised.")
    for name in ("snapshot_dt", "as_of_load_ts", "snapshot_ts"):
        value = params.get(name)
        if value is None:
            print(f"--   {name}: NOT FOUND -- borrower_history.txt's snapshots CTE may have changed shape; update _SNAPSHOT_PARAM in this script.")
        else:
            print(f"--   {name}: {value}")
    print(f"CREATE OR REPLACE VIEW {schema}.vw_bh_output AS")
    print(body.rstrip())
    print(";")


if __name__ == "__main__":
    main()
