"""
Direct verification of the "two simultaneous loans" hypothesis raised by
find_last_bad_loan.sql's results: for agents in the "old flag, clean now"
group who DO have a 30+ day loan somewhere in their history, that loan's
disbursement dates (Feb-June 2026) and closure dates (clustered on
Sept 10-11, 2026 -- suspiciously batch-like) implied it was STILL OPEN at
the July-31/August-17 scoring snapshot, at the same time a separate,
newer, fast-closing loan was ranked as each agent's "latest state" (the
loan has_unresolved_loan_at_snapshot is actually computed from). That
would mean the snapshot logic -- which only looks at the single
most-recently-STARTED loan per agent -- has a blind spot: it can miss an
older loan that's still open if a newer, faster loan started after it.

This does NOT trust that inference from dates alone. It pulls BOTH loan
records for the same agent side by side directly from the warehouse --
the old 30+-day loan and whatever loan was actually ranked "latest" (by
current_loan_start_date, mirroring loan_history_snapshot_query.txt's own
loans_ranked/latest_state logic exactly) -- and computes three explicit
checks per agent:

  - loan_identity_check: are these actually two DIFFERENT loan_uids, not
    one loan miscounted as two?
  - sequence_check: does the old loan have a LOWER loan_seq than the
    latest loan (the expected order if it's genuinely older)?
  - overlap_check: did the old loan's closure_date fall AFTER the latest
    loan's own start date (i.e., was the old loan still open when the
    new one began) -- direct confirmation of overlap, not inference.

Usage:
    python scripts\\generate_concurrent_loan_check_query.py ^
        --msisdn-file wl_bl_eval_matched_agents_old_flag_group_by_period.csv ^
        --out check_concurrent_loans.sql

Then run the generated .sql file against the warehouse. Rows with
loan_identity_check = 'DIFFERENT LOANS', sequence_check = 'OLD < LATEST
(expected order)', and overlap_check = 'OVERLAP CONFIRMED' are the ones
that directly confirm the blind-spot hypothesis; anything else is worth
looking at individually.
"""

import argparse
import sys
from pathlib import Path

import pandas as pd


def _normalize_msisdn(s: pd.Series) -> pd.Series:
    return s.astype(str).str.replace(r"[^0-9]", "", regex=True).replace("", pd.NA)


SQL_TEMPLATE = """-- ============================================================================
-- check_concurrent_loans.sql -- generated by
-- scripts/generate_concurrent_loan_check_query.py from {source_file}
-- ({n_msisdns:,} msisdns).
--
-- For agents with a 30+ day loan somewhere in their history (per
-- find_last_bad_loan.sql), pulls that loan AND the loan actually ranked
-- as their "latest state" (mirrors loan_history_snapshot_query.txt's
-- loans_ranked/latest_state logic: ROW_NUMBER by current_loan_start_date
-- DESC) side by side, to directly confirm -- not infer from dates alone --
-- whether the old bad loan was still open when a separate, newer, faster
-- loan started and became what has_unresolved_loan_at_snapshot is based on.
-- ============================================================================

WITH target_msisdns AS (
    SELECT msisdn FROM (VALUES
{values_block}
    ) AS t(msisdn)
),

bad_loans_ranked AS (
    SELECT
        ls.customer_msisdn AS msisdn,
        ls.loan_uid,
        ls.loan_seq,
        ls.current_loan_start_date,
        ls.closure_date,
        ls.loan_status,
        DATE_DIFF('day', ls.current_loan_start_date, ls.closure_date) AS tenure_days,

        ROW_NUMBER() OVER (
            PARTITION BY ls.customer_msisdn
            ORDER BY ls.closure_date DESC
        ) AS recency_rn

    FROM hive.analytics.tmp_loan_state ls
    JOIN target_msisdns m
      ON m.msisdn = ls.customer_msisdn

    WHERE ls.closure_date IS NOT NULL
      AND ls.loan_status IN ('SETTLED', 'CLOSED', 'OVERPAID')
      AND DATE_DIFF('day', ls.current_loan_start_date, ls.closure_date) >= 30
),

old_bad_loan AS (
    SELECT
        msisdn, loan_uid, loan_seq, current_loan_start_date,
        closure_date, loan_status, tenure_days
    FROM bad_loans_ranked
    WHERE recency_rn = 1
),

-- Mirrors loan_history_snapshot_query.txt's loans_ranked/latest_state
-- exactly: one row per msisdn, the loan with the latest start date.
latest_loans_ranked AS (
    SELECT
        ls.customer_msisdn AS msisdn,
        ls.loan_uid,
        ls.loan_seq,
        ls.current_loan_start_date,
        ls.closure_date,
        ls.loan_status,

        ROW_NUMBER() OVER (
            PARTITION BY ls.customer_msisdn
            ORDER BY
                ls.current_loan_start_date DESC,
                ls.loan_seq DESC,
                ls.loan_uid DESC
        ) AS loan_recency

    FROM hive.analytics.tmp_loan_state ls
    JOIN target_msisdns m
      ON m.msisdn = ls.customer_msisdn

    WHERE ls.loan_status <> 'NEVER_BORROWED'
),

latest_loan AS (
    SELECT msisdn, loan_uid, loan_seq, current_loan_start_date, closure_date, loan_status
    FROM latest_loans_ranked
    WHERE loan_recency = 1
)

SELECT
    o.msisdn,

    o.loan_uid AS old_bad_loan_uid,
    o.loan_seq AS old_bad_loan_seq,
    o.current_loan_start_date AS old_bad_loan_start,
    o.closure_date AS old_bad_loan_closure,
    o.loan_status AS old_bad_loan_status,
    o.tenure_days AS old_bad_loan_tenure_days,

    l.loan_uid AS latest_loan_uid,
    l.loan_seq AS latest_loan_seq,
    l.current_loan_start_date AS latest_loan_start,
    l.closure_date AS latest_loan_closure,
    l.loan_status AS latest_loan_status,

    CASE
        WHEN o.loan_uid = l.loan_uid THEN 'SAME LOAN'
        ELSE 'DIFFERENT LOANS'
    END AS loan_identity_check,

    CASE
        WHEN o.loan_seq < l.loan_seq THEN 'OLD < LATEST (expected order)'
        WHEN o.loan_seq > l.loan_seq THEN 'OLD > LATEST (unexpected)'
        ELSE 'EQUAL SEQ'
    END AS sequence_check,

    CASE
        WHEN o.closure_date > l.current_loan_start_date
            THEN 'OVERLAP CONFIRMED (old loan still open when latest started)'
        ELSE 'NO OVERLAP'
    END AS overlap_check

FROM old_bad_loan o
JOIN latest_loan l
  ON l.msisdn = o.msisdn

ORDER BY o.closure_date DESC;
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--msisdn-file", required=True,
                     help="CSV with a msisdn column -- can be the full old-flag-group list; "
                          "the query itself filters to those who actually have a 30+ day loan.")
    ap.add_argument("--out", default="check_concurrent_loans.sql")
    args = ap.parse_args()

    msisdn_path = Path(args.msisdn_file)
    if not msisdn_path.exists():
        sys.exit(f"ERROR: msisdn file not found: {msisdn_path}")

    df = pd.read_csv(msisdn_path)
    msisdn_col = "msisdn" if "msisdn" in df.columns else ("agent_msisdn" if "agent_msisdn" in df.columns else None)
    if msisdn_col is None:
        sys.exit(f"ERROR: {msisdn_path} has neither 'msisdn' nor 'agent_msisdn' column. "
                  f"Columns present: {list(df.columns)}")

    keys = _normalize_msisdn(df[msisdn_col]).dropna().unique().tolist()
    if not keys:
        sys.exit(f"ERROR: no usable msisdns found in {msisdn_path}")

    values_block = ",\n".join(f"        ('{k}')" for k in keys)
    sql = SQL_TEMPLATE.format(
        source_file=msisdn_path.name,
        n_msisdns=len(keys),
        values_block=values_block,
    )

    out_path = Path(args.out)
    out_path.write_text(sql, encoding="utf-8")
    print(f"Embedded {len(keys):,} msisdns from {msisdn_path}")
    print(f"Generated: {out_path}")
    print("Rows with loan_identity_check='DIFFERENT LOANS', sequence_check='OLD < LATEST "
          "(expected order)', and overlap_check='OVERLAP CONFIRMED' directly confirm the "
          "blind-spot hypothesis.")


if __name__ == "__main__":
    main()
