"""
The local CSVs only carry aggregated per-agent summaries (last_closed_loan_
tenure_days, max_tenure_days_last_5_closed_loans, avg_tenure_days_closed_loans)
-- none of them say WHEN a specific past loan closed. To find, for the
"old flag, clean now" group (last_closed_loan_tenure_days < 30 -- their most
recent loan closed too fast to be the Defaulter trigger), the closure date
of their MOST RECENT loan that actually took 30+ days, we need to scan each
agent's full loan history in the warehouse -- not available locally.

This generates a self-contained, ready-to-run SQL file that embeds the
exact msisdn list from a per-agent CSV (e.g.
wl_bl_eval_matched_agents_old_flag_group_by_period.csv, written by
check_old_flag_group_by_period.py) as a VALUES list, then queries
hive.analytics.tmp_loan_state directly: for each msisdn, ranks every loan
with tenure_days (computed the same validated way as this session's
tenure_days fix: DATE_DIFF('day', current_loan_start_date, closure_date))
>= 30 and loan_status IN ('SETTLED','CLOSED','OVERPAID') by closure_date
DESC, and returns the most recent one -- i.e. the closure date of the loan
that most plausibly triggered their Defaulter flag.

Usage:
    python scripts\\generate_last_bad_loan_query.py ^
        --msisdn-file wl_bl_eval_matched_agents_old_flag_group_by_period.csv ^
        --out find_last_bad_loan.sql

Then run the generated .sql file against the warehouse.
"""

import argparse
import sys
from pathlib import Path

import pandas as pd


def _normalize_msisdn(s: pd.Series) -> pd.Series:
    return s.astype(str).str.replace(r"[^0-9]", "", regex=True).replace("", pd.NA)


SQL_TEMPLATE = """-- ============================================================================
-- find_last_bad_loan.sql -- generated by scripts/generate_last_bad_loan_query.py
-- from {source_file} ({n_msisdns:,} msisdns).
--
-- For each embedded msisdn (the "old flag, clean now" group -- their most
-- recent CLOSED loan closes in under 30 days, so it cannot be the loan that
-- triggered "not paid back in the last 30 days"), finds their most recent
-- loan that DID take 30+ days to close -- the loan that most plausibly
-- triggered the Defaulter flag -- and reports its closure date.
--
-- tenure_days computed the same validated way as this session's tenure_days
-- fix: DATE_DIFF('day', current_loan_start_date, closure_date). loan_status
-- IN (...) required alongside closure_date IS NOT NULL, per this session's
-- confirmed finding that the source table populates closure_date on
-- genuinely non-terminal rows too.
-- ============================================================================

WITH target_msisdns AS (
    SELECT msisdn FROM (VALUES
{values_block}
    ) AS t(msisdn)
),

bad_loans_ranked AS (
    SELECT
        ls.customer_msisdn AS msisdn,
        ls.loan_uid,
        ls.current_loan_start_date,
        ls.closure_date,
        ls.loan_status,

        DATE_DIFF('day', ls.current_loan_start_date, ls.closure_date)
            AS tenure_days,

        ROW_NUMBER() OVER (
            PARTITION BY ls.customer_msisdn
            ORDER BY ls.closure_date DESC
        ) AS recency_rn

    FROM hive.analytics.tmp_loan_state ls
    JOIN target_msisdns m
      ON m.msisdn = ls.customer_msisdn

    WHERE ls.closure_date IS NOT NULL
      AND ls.loan_status IN ('SETTLED', 'CLOSED', 'OVERPAID')
      AND DATE_DIFF('day', ls.current_loan_start_date, ls.closure_date) >= 30
)

SELECT
    msisdn,
    loan_uid,
    current_loan_start_date AS last_bad_loan_disbursement_date,
    closure_date AS last_bad_loan_closure_date,
    tenure_days AS last_bad_loan_tenure_days,
    loan_status
FROM bad_loans_ranked
WHERE recency_rn = 1
ORDER BY closure_date DESC;

-- Agents from the {n_msisdns:,} in target_msisdns who have NO row in this
-- result at all never had ANY loan reach 30+ days per this table -- worth
-- checking separately, since for them the Defaulter flag would have no
-- observable basis in this loan-history data at all:
--
-- WITH target_msisdns AS (
--     SELECT msisdn FROM (VALUES
-- {values_block}
--     ) AS t(msisdn)
-- ),
-- bad_loans AS (
--     SELECT DISTINCT ls.customer_msisdn AS msisdn
--     FROM hive.analytics.tmp_loan_state ls
--     JOIN target_msisdns m ON m.msisdn = ls.customer_msisdn
--     WHERE ls.closure_date IS NOT NULL
--       AND ls.loan_status IN ('SETTLED', 'CLOSED', 'OVERPAID')
--       AND DATE_DIFF('day', ls.current_loan_start_date, ls.closure_date) >= 30
-- )
-- SELECT COUNT(*) AS n_with_no_30plus_day_loan_ever
-- FROM target_msisdns t
-- LEFT JOIN bad_loans b ON b.msisdn = t.msisdn
-- WHERE b.msisdn IS NULL;
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--msisdn-file", required=True,
                     help="CSV with a msisdn column, e.g. wl_bl_eval_matched_agents_old_flag_group_by_period.csv")
    ap.add_argument("--out", default="find_last_bad_loan.sql")
    args = ap.parse_args()

    msisdn_path = Path(args.msisdn_file)
    if not msisdn_path.exists():
        sys.exit(f"ERROR: msisdn file not found: {msisdn_path}")

    df = pd.read_csv(msisdn_path)
    msisdn_col = "msisdn" if "msisdn" in df.columns else ("agent_msisdn" if "agent_msisdn" in df.columns else None)
    if msisdn_col is None:
        sys.exit(f"ERROR: {msisdn_path} has neither 'msisdn' nor 'agent_msisdn' column. "
                  f"Columns present: {list(df.columns)}")

    keys = _normalize_msisdn(df[msisdn_col]).dropna().unique().tolist()
    if not keys:
        sys.exit(f"ERROR: no usable msisdns found in {msisdn_path}")

    values_block = ",\n".join(f"        ('{k}')" for k in keys)
    sql = SQL_TEMPLATE.format(
        source_file=msisdn_path.name,
        n_msisdns=len(keys),
        values_block=values_block,
    )

    out_path = Path(args.out)
    out_path.write_text(sql, encoding="utf-8")
    print(f"Embedded {len(keys):,} msisdns from {msisdn_path}")
    print(f"Generated: {out_path}")
    print(f"Run the main query, and separately the commented-out coverage query at the "
          f"bottom (see the note above it) to see how many have no 30+-day loan at all.")


if __name__ == "__main__":
    main()
