"""
Corrected version of the "any loan open at the snapshot" check. That naive
version would flag nearly every agent, since every loan is briefly OPEN
right after disbursement while still within its normal repayment window --
not a hidden default, just an ordinary in-progress loan.

This isolates the specific, meaningful case: across an agent's ENTIRE loan
history (not just the loan with the latest start date, which is all
has_unresolved_loan_at_snapshot / active_loan_days_aging_at_snapshot
actually look at), was there a loan that was ALREADY 30+ days old and STILL
OPEN as of the snapshot date -- i.e., genuinely, abnormally overdue at
scoring time, not just "a loan exists and hasn't closed yet." Evaluated
using each loan's state as recorded ON OR BEFORE the snapshot date (the
same no-look-ahead discipline used everywhere else in this pipeline) --
NOT the loan's current/today status, since we already confirmed these old
loans have since closed via an apparent Sept 10-11 batch event.

Usage:
    python scripts\\generate_hidden_old_open_loan_query.py ^
        --msisdn-file wl_bl_eval_matched_agents_old_flag_group_by_period.csv ^
        --snapshot-date 2026-08-17 ^
        --out find_hidden_old_open_loans.sql
"""

import argparse
import sys
from pathlib import Path

import pandas as pd


def _normalize_msisdn(s: pd.Series) -> pd.Series:
    return s.astype(str).str.replace(r"[^0-9]", "", regex=True).replace("", pd.NA)


SQL_TEMPLATE = """-- ============================================================================
-- find_hidden_old_open_loans.sql -- generated by
-- scripts/generate_hidden_old_open_loan_query.py from {source_file}
-- ({n_msisdns:,} msisdns), snapshot date {snapshot_date}.
--
-- has_unresolved_loan_at_snapshot only checks the SINGLE loan with the
-- latest current_loan_start_date per agent. This checks ALL of an agent's
-- loans: was there one that had ALREADY been open 30+ days as of the
-- snapshot AND was still open then (per its state as recorded on or
-- before the snapshot date -- not its current/today status, since these
-- loans have since closed via a later batch event). This deliberately
-- excludes ordinary, healthy in-progress loans (started shortly before
-- the snapshot, well within their normal repayment window) -- only a
-- loan already abnormally aged and unresolved counts.
-- ============================================================================

WITH target_msisdns AS (
    SELECT msisdn FROM (VALUES
{values_block}
    ) AS t(msisdn)
),

-- Each loan's most recent recorded state ON OR BEFORE the snapshot date --
-- mirrors the no-look-ahead discipline used throughout this pipeline
-- (e.g. prior_loan_state_candidates, scoring_state_candidates).
loan_state_as_of_snapshot AS (
    SELECT
        ls.customer_msisdn AS msisdn,
        ls.loan_uid,
        ls.loan_seq,
        ls.current_loan_start_date,
        ls.closure_date,
        ls.loan_status,
        ls.state_date,

        DATE_DIFF('day', ls.current_loan_start_date, DATE '{snapshot_date}')
            AS loan_age_at_snapshot_days,

        ROW_NUMBER() OVER (
            PARTITION BY ls.customer_msisdn, ls.loan_uid
            ORDER BY ls.state_date DESC, ls.inserted_ts DESC
        ) AS state_rn

    FROM hive.analytics.tmp_loan_state ls
    JOIN target_msisdns m
      ON m.msisdn = ls.customer_msisdn

    WHERE ls.loan_status <> 'NEVER_BORROWED'
      AND ls.state_date <= DATE '{snapshot_date}'
),

hidden_old_open_loans AS (
    SELECT *
    FROM loan_state_as_of_snapshot
    WHERE state_rn = 1
      AND loan_age_at_snapshot_days >= 30
      AND loan_status IN ('OPEN', 'OPEN_PRE_WINDOW', 'ANOMALY_OPEN')
)

-- Per-agent detail: every qualifying hidden old open loan.
SELECT
    msisdn,
    loan_uid,
    loan_seq,
    current_loan_start_date,
    loan_status AS status_as_of_snapshot,
    loan_age_at_snapshot_days,
    closure_date AS closure_date_as_currently_known
FROM hidden_old_open_loans
ORDER BY loan_age_at_snapshot_days DESC;


-- ============================================================================
-- Second, fully separate query -- run this one on its own afterward.
-- Overall count of agents affected, out of the {n_msisdns:,} embedded above.
-- (A CTE only lives for the single statement that defines it, so this
-- repeats its own full WITH clause rather than assuming the query above's
-- CTEs are still queryable.)
-- ============================================================================

WITH target_msisdns AS (
    SELECT msisdn FROM (VALUES
{values_block}
    ) AS t(msisdn)
),

loan_state_as_of_snapshot AS (
    SELECT
        ls.customer_msisdn AS msisdn,
        ls.loan_status,

        DATE_DIFF('day', ls.current_loan_start_date, DATE '{snapshot_date}')
            AS loan_age_at_snapshot_days,

        ROW_NUMBER() OVER (
            PARTITION BY ls.customer_msisdn, ls.loan_uid
            ORDER BY ls.state_date DESC, ls.inserted_ts DESC
        ) AS state_rn

    FROM hive.analytics.tmp_loan_state ls
    JOIN target_msisdns m
      ON m.msisdn = ls.customer_msisdn

    WHERE ls.loan_status <> 'NEVER_BORROWED'
      AND ls.state_date <= DATE '{snapshot_date}'
)

SELECT
    (SELECT COUNT(*) FROM target_msisdns) AS n_total_msisdns_checked,

    COUNT(DISTINCT CASE
        WHEN state_rn = 1
         AND loan_age_at_snapshot_days >= 30
         AND loan_status IN ('OPEN', 'OPEN_PRE_WINDOW', 'ANOMALY_OPEN')
        THEN msisdn
    END) AS n_with_hidden_old_open_loan

FROM loan_state_as_of_snapshot;
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--msisdn-file", required=True)
    ap.add_argument("--snapshot-date", default="2026-08-17",
                     help="The loan-history-snapshot's own snapshot_dt (loan_history_snapshot_query.txt), "
                          "not the engine's --snapshot-date -- has_unresolved_loan_at_snapshot is computed "
                          "as of this date.")
    ap.add_argument("--out", default="find_hidden_old_open_loans.sql")
    args = ap.parse_args()

    msisdn_path = Path(args.msisdn_file)
    if not msisdn_path.exists():
        sys.exit(f"ERROR: msisdn file not found: {msisdn_path}")

    df = pd.read_csv(msisdn_path)
    msisdn_col = "msisdn" if "msisdn" in df.columns else ("agent_msisdn" if "agent_msisdn" in df.columns else None)
    if msisdn_col is None:
        sys.exit(f"ERROR: {msisdn_path} has neither 'msisdn' nor 'agent_msisdn' column. "
                  f"Columns present: {list(df.columns)}")

    keys = _normalize_msisdn(df[msisdn_col]).dropna().unique().tolist()
    if not keys:
        sys.exit(f"ERROR: no usable msisdns found in {msisdn_path}")

    values_block = ",\n".join(f"        ('{k}')" for k in keys)
    sql = SQL_TEMPLATE.format(
        source_file=msisdn_path.name,
        n_msisdns=len(keys),
        snapshot_date=args.snapshot_date,
        values_block=values_block,
    )

    out_path = Path(args.out)
    out_path.write_text(sql, encoding="utf-8")
    print(f"Embedded {len(keys):,} msisdns from {msisdn_path}")
    print(f"Generated: {out_path}")
    print("Run the first query for per-agent detail, then the second (fully separate) "
          "query for the overall n_with_hidden_old_open_loan count.")


if __name__ == "__main__":
    main()
