"""
Phase 2.2 — Loan repayment features, labelling, and leakage audit.

Provides:
- ``classify_agent_loan_status``   – converts has_ever_loan to has_loan_history flag
- ``add_thin_file_flags``          – adds thin_file_flag and thin_file_pd_prior
- ``compute_bad_flags``            – computes hard_bad_flag and bad_state (30-day target)
- ``leakage_audit_phase_2_2``      – correlation / dominance leakage scan
- ``run_phase_2_2_repayment_pd_features`` – orchestrates repayment feature merge
"""

from __future__ import annotations

from typing import Optional, Tuple

import numpy as np
import pandas as pd

from pd_model.config.feature_config import NON_BEHAVIOURAL_COLS, REPAYMENT_FORBIDDEN_SUBSTRINGS
from pd_model.config.model_config import DEFAULT_CONFIG, ModelConfig
from pd_model.logging_config import get_logger
from pd_model.validation.schema import require_columns

logger = get_logger(__name__)


# ======================================================================== #
# Agent classification helpers
# ======================================================================== #

def classify_agent_loan_status(df_pd: pd.DataFrame) -> pd.DataFrame:
    """
    Convert ``has_ever_loan`` (from repayment merge) into ``has_loan_history`` and
    ``is_new_agent`` binary flags.

    Args:
        df_pd: Modelling DataFrame; must contain ``has_ever_loan``.

    Returns:
        Copy of *df_pd* with ``has_loan_history`` and ``is_new_agent`` added.

    Raises:
        RuntimeError: If ``has_ever_loan`` is absent.
    """
    require_columns(df_pd, ["has_ever_loan"], context="classify_agent_loan_status")
    df = df_pd.copy()

    df["has_loan_history"] = df["has_ever_loan"].astype(int)

    assert set(df["has_loan_history"].unique()).issubset({0, 1}), (
        "has_loan_history contains values outside {0, 1}"
    )
    assert not df["has_loan_history"].isna().any(), (
        "has_loan_history contains NaNs"
    )

    df["is_new_agent"] = (df["has_loan_history"] == 0).astype(int)

    logger.info(
        "classify_agent_loan_status: %d agents with loan history, %d new agents",
        int(df["has_loan_history"].sum()),
        int(df["is_new_agent"].sum()),
    )
    return df


def add_thin_file_flags(
    df_pd: pd.DataFrame,
    cfg: ModelConfig = DEFAULT_CONFIG,
) -> pd.DataFrame:
    """
    Add ``thin_file_flag`` (1 = no loan history) and ``thin_file_pd_prior``
    (policy fallback PD, stored for reference but NOT used in training).

    Args:
        df_pd: Modelling DataFrame; must contain ``has_loan_history``.
        cfg:   Model config supplying ``thin_file_pd_prior``.

    Returns:
        Copy of *df_pd* with ``thin_file_flag`` and ``thin_file_pd_prior``.
    """
    require_columns(df_pd, ["has_loan_history"], context="add_thin_file_flags")
    df = df_pd.copy()

    df["thin_file_flag"] = (df["has_loan_history"] == 0).astype(int)
    df["thin_file_pd_prior"] = np.where(
        df["thin_file_flag"] == 1, cfg.thin_file_pd_prior, 0.0
    )

    n_thin = int(df["thin_file_flag"].sum())
    logger.info(
        "add_thin_file_flags: %d thin-file agents (thin_file_pd_prior=%.2f)",
        n_thin,
        cfg.thin_file_pd_prior,
    )
    return df


# ======================================================================== #
# Label computation
# ======================================================================== #

def compute_bad_flags(df_pd: pd.DataFrame) -> pd.DataFrame:
    """
    Compute:
    - ``hard_bad_flag``  – short-term monitoring flag (repayment coverage + penalties)
    - ``bad_state``      – PD target (forward-looking 30-day bad indicator)

    ``bad_state_30D`` must already exist (generated upstream by SQL / data pipeline).

    Args:
        df_pd: Modelling DataFrame.

    Returns:
        Copy of *df_pd* with ``hard_bad_flag`` and ``bad_state`` added / refreshed.

    Raises:
        RuntimeError: If ``bad_state_30D`` is absent.
    """
    df = df_pd.copy()

    # Hard bad flag — monitoring signal
    repayment_coverage_1M = df.get("repayment_coverage_1M", pd.Series(1, index=df.index))
    penalties_1M = df.get("penalties_1M", pd.Series(0, index=df.index))
    repayment_val_1M = df.get("repayment_val_1M", pd.Series(1, index=df.index))

    df["hard_bad_flag"] = (
        (repayment_coverage_1M < 0.3)
        & (penalties_1M > 0)
        & (repayment_val_1M == 0)
    ).astype(int)

    # PD target — forward-looking 30-day
    if "bad_state_30D" not in df.columns:
        raise RuntimeError(
            "[compute_bad_flags] Missing required column 'bad_state_30D' "
            "(must be generated by the SQL pipeline before calling this function)."
        )

    df["bad_state"] = (df["bad_state_30D"].fillna(0) > 0).astype(int)

    assert set(df["bad_state"].unique()).issubset({0, 1}), (
        "bad_state contains values outside {0, 1}"
    )
    assert not df["bad_state"].isna().any(), "bad_state contains NaNs"

    logger.info(
        "compute_bad_flags: bad_state=%d/%d (%.2f%%), hard_bad_flag=%d",
        int(df["bad_state"].sum()),
        len(df),
        float(df["bad_state"].mean()) * 100,
        int(df["hard_bad_flag"].sum()),
    )
    return df


# ======================================================================== #
# Leakage audit
# ======================================================================== #

def leakage_audit_phase_2_2(
    df_pd: pd.DataFrame,
    snapshot_col: str = "snapshot_dt",
    txn_max_col: str = "max_txn_dt",
    label_cols: Tuple[str, ...] = (
        "bad_state", "current_dpd", "ever_written_off", "ever_in_collections"
    ),
    hard_fail: bool = True,
    cfg: ModelConfig = DEFAULT_CONFIG,
    verbose: bool = True,
) -> pd.DataFrame:
    """
    Run four leakage checks on the modelling DataFrame:

    1. **TARGET_LEAKAGE**   – label-related columns present in feature table.
    2. **TIME_LEAKAGE**     – transaction timestamps post-dating the snapshot.
    3. **LABEL_PROXY**      – features with |corr| > threshold against ``bad_state``.
    4. **BINARY_DOMINANCE** – binary columns where bad-rate jump exceeds threshold.

    Args:
        df_pd:        Modelling DataFrame.
        snapshot_col: Column holding the snapshot date.
        txn_max_col:  Column holding the maximum transaction date (may be absent).
        label_cols:   Columns considered target-adjacent.
        hard_fail:    If ``True``, raise ``RuntimeError`` on any HIGH finding.
        cfg:          Model config for correlation and dominance thresholds.
        verbose:      If ``True``, log the audit report.

    Returns:
        Audit report as a DataFrame with columns
        ``[check, column, severity, message]``.

    Raises:
        RuntimeError: On HIGH findings when ``hard_fail=True``.
    """
    if not isinstance(df_pd, pd.DataFrame):
        raise TypeError("df_pd must be a pandas DataFrame")

    audit_rows = []

    # ------------------------------------------------------------------ #
    # 1) Target leakage
    # ------------------------------------------------------------------ #
    for col_name in df_pd.columns:
        if col_name in label_cols and col_name != "bad_state":
            audit_rows.append(
                {
                    "check": "TARGET_LEAKAGE",
                    "column": col_name,
                    "severity": "HIGH",
                    "message": f"Label-related column present in feature table: {col_name}",
                }
            )

    # ------------------------------------------------------------------ #
    # 2) Future-time leakage
    # ------------------------------------------------------------------ #
    if snapshot_col in df_pd.columns and txn_max_col in df_pd.columns:
        snap_ser = df_pd[snapshot_col]
        txn_ser = df_pd[txn_max_col]

        if not pd.api.types.is_datetime64_any_dtype(snap_ser):
            snap_ser = pd.to_datetime(snap_ser, errors="coerce")
        if not pd.api.types.is_datetime64_any_dtype(txn_ser):
            txn_ser = pd.to_datetime(txn_ser, errors="coerce")

        future_mask = txn_ser.notna() & snap_ser.notna() & (txn_ser > snap_ser)
        if bool(future_mask.any()):
            n_future = int(future_mask.sum())
            audit_rows.append(
                {
                    "check": "TIME_LEAKAGE",
                    "column": txn_max_col,
                    "severity": "HIGH",
                    "message": f"{n_future} rows have transactions after snapshot date",
                }
            )

    # ------------------------------------------------------------------ #
    # 3) Label-proxy correlation
    # ------------------------------------------------------------------ #
    if "bad_state" in df_pd.columns:
        y = pd.to_numeric(df_pd["bad_state"], errors="coerce")
        if y.notna().sum() > 0:
            numeric_cols = [
                c
                for c in df_pd.columns
                if c != "bad_state" and pd.api.types.is_numeric_dtype(df_pd[c])
            ]
            if len(numeric_cols) > cfg.max_corr_cols:
                logger.warning(
                    "leakage_audit: limiting correlation sweep to first %d of %d numeric cols",
                    cfg.max_corr_cols,
                    len(numeric_cols),
                )
                numeric_cols = numeric_cols[: cfg.max_corr_cols]

            for col_name in numeric_cols:
                x = pd.to_numeric(df_pd[col_name], errors="coerce")
                valid_mask = x.notna() & y.notna()
                if int(valid_mask.sum()) < 50:
                    continue
                corr_val = x.loc[valid_mask].corr(y.loc[valid_mask])
                if pd.isna(corr_val):
                    continue
                abs_corr = float(abs(corr_val))
                if abs_corr > cfg.corr_high:
                    audit_rows.append(
                        {
                            "check": "LABEL_PROXY",
                            "column": col_name,
                            "severity": "HIGH",
                            "message": f"Very high correlation with bad_state: {corr_val:.3f}",
                        }
                    )
                elif abs_corr > cfg.corr_med:
                    audit_rows.append(
                        {
                            "check": "LABEL_PROXY",
                            "column": col_name,
                            "severity": "MEDIUM",
                            "message": f"High correlation with bad_state: {corr_val:.3f}",
                        }
                    )

    # ------------------------------------------------------------------ #
    # 4) Binary dominance
    # ------------------------------------------------------------------ #
    if "bad_state" in df_pd.columns:
        y = pd.to_numeric(df_pd["bad_state"], errors="coerce")
        if y.notna().sum() > 0:
            for col_name in df_pd.columns:
                if col_name == "bad_state":
                    continue
                ser = df_pd[col_name]
                if int(ser.dropna().nunique()) != 2:
                    continue
                vals = list(pd.Series(ser.dropna().unique()).sort_values())
                if len(vals) != 2:
                    continue
                v0, v1 = vals[0], vals[1]
                mask0, mask1 = ser == v0, ser == v1
                if int(mask0.sum()) < 30 or int(mask1.sum()) < 30:
                    continue
                rate_0 = float(y.loc[mask0].mean())
                rate_1 = float(y.loc[mask1].mean())
                jump = float(abs(rate_1 - rate_0))
                if np.isfinite(jump) and jump > cfg.dominance_high:
                    audit_rows.append(
                        {
                            "check": "BINARY_DOMINANCE",
                            "column": col_name,
                            "severity": "HIGH",
                            "message": (
                                f"Bad rate jump {jump:.3f} between "
                                f"{v0} and {v1}"
                            ),
                        }
                    )

    # ------------------------------------------------------------------ #
    # Report
    # ------------------------------------------------------------------ #
    audit_report = pd.DataFrame(audit_rows)

    if verbose:
        if not audit_report.empty:
            sev_order = {"HIGH": 0, "MEDIUM": 1, "LOW": 2}
            tmp = audit_report.copy()
            tmp["_ord"] = tmp["severity"].map(sev_order).fillna(9).astype(int)
            tmp = tmp.sort_values(["_ord", "check", "column"]).drop(columns=["_ord"])
            logger.warning("LEAKAGE AUDIT — %d findings:\n%s", len(tmp), tmp.to_string(index=False))
        else:
            logger.info("Leakage audit passed — no red flags detected")

    if hard_fail and not audit_report.empty:
        high_df = audit_report[audit_report["severity"] == "HIGH"].copy()
        if not high_df.empty:
            high_df = high_df.sort_values(["check", "column"])
            lines = ["HARD LEAKAGE DETECTED — FIX BEFORE MODELING"]
            lines.append(f"HIGH findings ({len(high_df)}):")
            for _, row in high_df.iterrows():
                lines.append(f"  - {row['check']} | {row['column']} | {row['message']}")
            raise RuntimeError("\n".join(lines))

    return audit_report


# ======================================================================== #
# Repayment feature pipeline
# ======================================================================== #

def run_phase_2_2_repayment_pd_features(
    df_pd: pd.DataFrame,
    df_repayments: pd.DataFrame,
    cfg: ModelConfig = DEFAULT_CONFIG,
    verbose: bool = False,
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Merge repayment features into the PD modelling table and compute labels.

    Steps
    -----
    1. Normalise column names and snapshot-date formats on both sides.
    2. Compute repayment behavioural features (DPD, penalties, consistency, etc.).
    3. Construct a unique repayment frame and merge it into *df_pd*.
    4. Bring the label (``bad_state_30D``) across separately.
    5. Call :func:`compute_bad_flags` to create ``bad_state`` and ``hard_bad_flag``.
    6. Apply thin-file guardrail (nullify repayment behaviour for thin-file agents).
    7. Validate date columns and assert no schema corruption.

    Args:
        df_pd:        Modelling DataFrame (output of Phase 2.1).
        df_repayments: Raw repayments snapshot.
        cfg:          Model config.
        verbose:      If ``True``, log extra diagnostics.

    Returns:
        Tuple of ``(df_pd_out, df_repayments_out)`` where *df_repayments_out* is
        kept for debugging.
    """
    df_pd = df_pd.copy()
    df_repayments = df_repayments.copy()

    # Strip whitespace from column names
    df_pd.columns = [c.strip() for c in df_pd.columns]
    df_repayments.columns = [c.strip() for c in df_repayments.columns]

    # Normalise agent ID column name
    if "agent_msisdn" not in df_repayments.columns and "msisdn" in df_repayments.columns:
        df_repayments = df_repayments.rename(columns={"msisdn": "agent_msisdn"})
    if "agent_msisdn" not in df_pd.columns and "msisdn" in df_pd.columns:
        df_pd = df_pd.rename(columns={"msisdn": "agent_msisdn"})

    require_columns(df_pd, ["agent_msisdn"], context="run_phase_2_2")
    require_columns(df_repayments, ["agent_msisdn"], context="run_phase_2_2")

    # Coerce agent_msisdn to string on both sides so int64 vs str doesn't
    # silently produce zero merge matches (e.g. 256787530736 vs '256787530736')
    df_pd["agent_msisdn"] = df_pd["agent_msisdn"].astype(str).str.strip()
    df_repayments["agent_msisdn"] = df_repayments["agent_msisdn"].astype(str).str.strip()

    eps = cfg.eps

    # ------------------------------------------------------------------ #
    # Internal helpers
    # ------------------------------------------------------------------ #
    def _pick_col(df_in: pd.DataFrame, candidates: list) -> Optional[str]:
        for c in candidates:
            if c in df_in.columns:
                return c
        return None

    def _to_num(s: pd.Series) -> pd.Series:
        return pd.to_numeric(s, errors="coerce")

    def _coerce_dt(s: pd.Series) -> pd.Series:
        if pd.api.types.is_datetime64_any_dtype(s):
            return s
        dt1 = pd.to_datetime(s, errors="coerce")
        if dt1.notna().sum() > 0:
            return dt1
        return pd.to_datetime(s, errors="coerce", dayfirst=True)

    # ------------------------------------------------------------------ #
    # Snapshot date parsing
    # ------------------------------------------------------------------ #
    snapshot_col: Optional[str] = None
    if "snapshot_dt" in df_repayments.columns:
        snapshot_col = "snapshot_dt"
    elif "tbl_dt" in df_repayments.columns:
        snapshot_col = "tbl_dt"

    assert snapshot_col is not None, (
        "[run_phase_2_2] No snapshot column found in df_repayments "
        "(expected snapshot_dt or tbl_dt)"
    )

    if not pd.api.types.is_datetime64_any_dtype(df_repayments[snapshot_col]):
        raw = df_repayments[snapshot_col]
        total = len(raw)

        # Try YYYYMMDD integer format first (e.g. 20251115 stored as int64 or
        # "20251115" as string) — generic pd.to_datetime treats integers as
        # nanoseconds since epoch producing 1970-era dates, so check this first.
        looks_yyyymmdd = (
            pd.to_numeric(raw, errors="coerce")
            .between(20000101, 21001231, inclusive="both")
            .fillna(False)
        )
        if looks_yyyymmdd.any():
            snap_dt = pd.to_datetime(raw.astype(str), format="%Y%m%d", errors="coerce")
            parsed_fmt = "YYYYMMDD"
        else:
            snap_dt = pd.to_datetime(raw, errors="coerce")
            parsed_fmt = "generic ISO"

        if snap_dt.notna().sum() == 0:
            snap_dt = pd.to_datetime(raw, errors="coerce", dayfirst=True)
            parsed_fmt = "dayfirst"

        if snap_dt.notna().sum() == 0:
            snap_dt = pd.to_datetime(raw.astype(str), format="%Y%m%d", errors="coerce")
            parsed_fmt = "YYYYMMDD"

        parsed_count = int(snap_dt.notna().sum())
        parse_rate = parsed_count / max(total, 1)

        if parse_rate < 0.99:
            logger.warning(
                "run_phase_2_2: snapshot_dt parse rate %.1f%% (format: %s) — "
                "%d/%d rows unparsed",
                parse_rate * 100,
                parsed_fmt,
                total - parsed_count,
                total,
            )
        else:
            logger.info(
                "run_phase_2_2: parsed snapshot_dt using format '%s' "
                "(%d/%d rows)",
                parsed_fmt,
                parsed_count,
                total,
            )

        df_repayments[snapshot_col] = snap_dt

    assert df_repayments[snapshot_col].notna().any(), (
        "[run_phase_2_2] Snapshot dates could not be parsed in df_repayments"
    )
    assert (
        df_repayments[snapshot_col].dropna() > pd.Timestamp("2000-01-01")
    ).all(), "[run_phase_2_2] Invalid snapshot_dt values detected"

    # ------------------------------------------------------------------ #
    # Date anchor columns
    # ------------------------------------------------------------------ #
    anchor_cols = [
        "Last_disbursement_date", "last_disbursement_date",
        "Last_repayment_date", "last_repayment_date",
    ]
    for c in anchor_cols:
        if c not in df_repayments.columns:
            continue
        if pd.api.types.is_datetime64_any_dtype(df_repayments[c]):
            continue
        raw = df_repayments[c]
        looks_yyyymmdd = raw.astype(str).str.fullmatch(r"\d{8}").fillna(False)
        if looks_yyyymmdd.any():
            parsed = pd.to_datetime(raw.astype(str), format="%Y%m%d", errors="coerce")
        else:
            parsed = pd.to_datetime(raw, errors="coerce")
        if parsed.notna().sum() == 0:
            parsed = pd.to_datetime(raw, errors="coerce", dayfirst=True)
        df_repayments[c] = parsed

    # ------------------------------------------------------------------ #
    # Repayment gap / implied DPD
    # ------------------------------------------------------------------ #
    repay_date_col = _pick_col(df_repayments, ["Last_repayment_date", "last_repayment_date"])
    if repay_date_col is not None:
        df_repayments["repayment_gap_days"] = (
            df_repayments[snapshot_col] - df_repayments[repay_date_col]
        ).dt.days
        df_repayments.loc[df_repayments["repayment_gap_days"] < 0, "repayment_gap_days"] = np.nan

    # ------------------------------------------------------------------ #
    # Penalty features
    # ------------------------------------------------------------------ #
    pen_candidates = [
        "penalties_1M", "penalties_3M", "penalties_6M",
        "penalties_1m", "penalties_3m", "penalties_6m",
    ]
    penalty_cols = [c for c in pen_candidates if c in df_repayments.columns]
    if penalty_cols:
        df_repayments["ever_penalized"] = (
            df_repayments[penalty_cols].fillna(0).sum(axis=1) > 0
        ).astype(int)

    pen_6m_col = _pick_col(df_repayments, ["penalties_6M", "penalties_6m"])
    if pen_6m_col is not None:
        df_repayments["penalty_frequency_6M"] = _to_num(df_repayments[pen_6m_col]).fillna(0)

    pen_1m_col = _pick_col(df_repayments, ["penalties_1M", "penalties_1m"])
    pen_3m_col = _pick_col(df_repayments, ["penalties_3M", "penalties_3m"])
    if pen_1m_col and pen_3m_col:
        p1 = _to_num(df_repayments[pen_1m_col]).fillna(0)
        p3 = _to_num(df_repayments[pen_3m_col]).fillna(0)
        df_repayments["penalty_roll_forward"] = ((p3 > 0) & (p1 > 0)).astype(int)
        df_repayments["cured_after_penalty"] = ((p3 > 0) & (p1 == 0)).astype(int)

    # ------------------------------------------------------------------ #
    # DPD flags
    # ------------------------------------------------------------------ #
    if "repayment_gap_days" in df_repayments.columns:
        df_repayments["max_dpd_bucket"] = pd.cut(
            _to_num(df_repayments["repayment_gap_days"]),
            bins=[-1, 0, 30, 60, 90, 999999],
            labels=[0, 1, 2, 3, 4],
        ).astype(float)
        gap = _to_num(df_repayments["repayment_gap_days"])
        df_repayments["dpd_30_plus"] = (gap > 30).astype(int)
        df_repayments["dpd_60_plus"] = (gap > 60).astype(int)
        df_repayments["dpd_90_plus"] = (gap > 90).astype(int)

    # ------------------------------------------------------------------ #
    # Repayment consistency and trend
    # ------------------------------------------------------------------ #
    rep_vol_m1 = _pick_col(df_repayments, ["Repayment_vol_M1", "repayment_vol_m1"])
    rep_vol_m2 = _pick_col(df_repayments, ["Repayment_vol_M2", "repayment_vol_m2"])
    rep_vol_m3 = _pick_col(df_repayments, ["Repayment_vol_M3", "repayment_vol_m3"])

    if rep_vol_m1 and rep_vol_m2 and rep_vol_m3:
        v1 = (_to_num(df_repayments[rep_vol_m1]).fillna(0) > 0).astype(int)
        v2 = (_to_num(df_repayments[rep_vol_m2]).fillna(0) > 0).astype(int)
        v3 = (_to_num(df_repayments[rep_vol_m3]).fillna(0) > 0).astype(int)
        df_repayments["repayment_consistency_3M"] = v1 + v2 + v3

    if rep_vol_m1:
        df_repayments["missed_repayment_last_month"] = (
            _to_num(df_repayments[rep_vol_m1]).fillna(0) == 0
        ).astype(int)

    rep_val_6m_col = _pick_col(df_repayments, ["repayment_val_6M", "repayment_val_6m"])
    disb_val_6m_col = _pick_col(df_repayments, ["disbursement_val_6M", "disbursement_val_6m"])
    if rep_val_6m_col and disb_val_6m_col:
        rep_val = _to_num(df_repayments[rep_val_6m_col]).abs()
        disb_val = _to_num(df_repayments[disb_val_6m_col])
        df_repayments["repayment_coverage_ratio_6M"] = rep_val / (disb_val + eps)

    if "ever_penalized" in df_repayments.columns:
        df_repayments["ever_delinquent_flag"] = (
            _to_num(df_repayments["ever_penalized"]).fillna(0).astype(int)
        )

    rep_val_m1_col = _pick_col(df_repayments, ["Repayment_val_M1", "repayment_val_m1"])
    rep_val_m2_col = _pick_col(df_repayments, ["Repayment_val_M2", "repayment_val_m2"])
    if rep_val_m1_col and rep_val_m2_col:
        m1 = _to_num(df_repayments[rep_val_m1_col]).abs()
        m2 = _to_num(df_repayments[rep_val_m2_col]).abs()
        df_repayments["repayment_trend_deteriorating"] = (m1 < m2).astype(int)

    disb_6m_col = _pick_col(df_repayments, ["disbursement_val_6M", "disbursement_val_6m"])
    rep_6m_col = _pick_col(df_repayments, ["repayment_val_6M", "repayment_val_6m"])
    if disb_6m_col and rep_6m_col:
        disb6 = _to_num(df_repayments[disb_6m_col])
        rep6 = _to_num(df_repayments[rep_6m_col]).abs()
        df_repayments["net_exposure_6M"] = disb6 - rep6
        df_repayments["currently_outstanding_flag"] = (
            df_repayments["net_exposure_6M"] > 0
        ).astype(int)

    if all(c in df_repayments.columns for c in ["dpd_30_plus", "dpd_60_plus"]):
        df_repayments["chronic_delinquency_flag"] = (
            (df_repayments["dpd_30_plus"].fillna(0).astype(int) == 1)
            & (df_repayments["dpd_60_plus"].fillna(0).astype(int) == 1)
        ).astype(int)

    # ------------------------------------------------------------------ #
    # Standardise join keys
    # ------------------------------------------------------------------ #
    df_pd_out = df_pd.copy()
    df_repayments_out = df_repayments.copy()

    rep_id_col = _pick_col(df_repayments_out, ["agent_msisdn", "msisdn"])
    pd_id_col = _pick_col(df_pd_out, ["agent_msisdn", "msisdn"])
    assert rep_id_col is not None, "[run_phase_2_2] df_repayments missing msisdn/agent_msisdn"
    assert pd_id_col is not None, "[run_phase_2_2] df_pd missing agent_msisdn/msisdn"

    if rep_id_col != "agent_msisdn":
        df_repayments_out = df_repayments_out.rename(columns={rep_id_col: "agent_msisdn"})
    if pd_id_col != "agent_msisdn":
        df_pd_out = df_pd_out.rename(columns={pd_id_col: "agent_msisdn"})

    df_repayments_out["agent_msisdn"] = df_repayments_out["agent_msisdn"].astype(str)
    df_pd_out["agent_msisdn"] = df_pd_out["agent_msisdn"].astype(str)

    snapshot_key: Optional[str] = None
    if "snapshot_dt" in df_pd_out.columns and "snapshot_dt" in df_repayments_out.columns:
        snapshot_key = "snapshot_dt"
    elif "tbl_dt" in df_pd_out.columns and "tbl_dt" in df_repayments_out.columns:
        snapshot_key = "tbl_dt"

    assert snapshot_key is not None, (
        "[run_phase_2_2] Need a common snapshot key in both df_pd and df_repayments "
        "(snapshot_dt preferred, else tbl_dt)."
    )

    if snapshot_key != "snapshot_dt":
        df_pd_out = df_pd_out.rename(columns={snapshot_key: "snapshot_dt"})
        df_repayments_out = df_repayments_out.rename(columns={snapshot_key: "snapshot_dt"})

    df_pd_out["snapshot_dt"] = _coerce_dt(df_pd_out["snapshot_dt"])
    df_repayments_out["snapshot_dt"] = _coerce_dt(df_repayments_out["snapshot_dt"])

    assert df_pd_out["snapshot_dt"].notna().any(), (
        "[run_phase_2_2] df_pd snapshot_dt could not be parsed"
    )
    assert df_repayments_out["snapshot_dt"].notna().any(), (
        "[run_phase_2_2] df_repayments snapshot_dt could not be parsed"
    )

    # ------------------------------------------------------------------ #
    # Identify repayment numeric behavioural features
    # ------------------------------------------------------------------ #
    repayment_date_cols = [
        c
        for c in df_repayments_out.columns
        if pd.api.types.is_datetime64_any_dtype(df_repayments_out[c])
    ]

    non_behav_lower = {c.strip().lower() for c in NON_BEHAVIOURAL_COLS}
    repay_dates_lower = {c.strip().lower() for c in repayment_date_cols}

    repayment_numeric_features = [
        c
        for c in df_repayments_out.columns
        if c.strip().lower() not in non_behav_lower
        and c.strip().lower() not in repay_dates_lower
        and pd.api.types.is_numeric_dtype(df_repayments_out[c])
    ]

    # Hard guards
    repayment_numeric_lower = {c.strip().lower() for c in repayment_numeric_features}
    leaked_exact = sorted(repayment_numeric_lower & non_behav_lower)
    assert not leaked_exact, (
        "[run_phase_2_2] NON_BEHAVIOURAL_COLS leaked into repayment_numeric_features: "
        + ", ".join(leaked_exact)
    )

    leaked_pattern = sorted(
        c
        for c in repayment_numeric_features
        if any(sub in c.strip().lower() for sub in REPAYMENT_FORBIDDEN_SUBSTRINGS)
    )
    assert not leaked_pattern, (
        "[run_phase_2_2] Label / forward-looking columns leaked via name patterns: "
        + ", ".join(leaked_pattern)
    )

    assert repayment_numeric_features, (
        "[run_phase_2_2] No numeric repayment behavioural features detected"
    )

    # ------------------------------------------------------------------ #
    # Label merge (separate from behavioural features)
    # ------------------------------------------------------------------ #
    label_col: Optional[str] = None
    for cand in ["bad_state_30D", "bad_state_30d", "bad_state"]:
        if cand in df_repayments_out.columns:
            label_col = cand
            break

    if label_col is not None and "bad_state_30D" not in df_pd_out.columns:
        df_labels = (
            df_repayments_out.groupby(["agent_msisdn", "snapshot_dt"], as_index=False)[
                label_col
            ].max()
        )
        if label_col != "bad_state_30D":
            df_labels = df_labels.rename(columns={label_col: "bad_state_30D"})
        df_pd_out = df_pd_out.merge(
            df_labels,
            on=["agent_msisdn", "snapshot_dt"],
            how="left",
            validate="one_to_one",
        )

    # ------------------------------------------------------------------ #
    # Behavioural feature merge
    # ------------------------------------------------------------------ #
    df_repayments_numeric = df_repayments_out[
        ["agent_msisdn", "snapshot_dt"] + repayment_numeric_features
    ].copy()

    dup_rep = df_repayments_numeric.duplicated(
        subset=["agent_msisdn", "snapshot_dt"], keep=False
    ).sum()
    assert int(dup_rep) == 0, (
        "[run_phase_2_2] Repayment feature table is not unique per "
        "(agent_msisdn, snapshot_dt). Aggregate/dedupe before merge."
    )

    dup_pd_pre = df_pd_out.duplicated(
        subset=["agent_msisdn", "snapshot_dt"], keep=False
    ).sum()
    assert int(dup_pd_pre) == 0, (
        "[run_phase_2_2] df_pd is not unique per (agent_msisdn, snapshot_dt) before merge"
    )

    df_pd_out = df_pd_out.merge(
        df_repayments_numeric,
        on=["agent_msisdn", "snapshot_dt"],
        how="left",
        validate="one_to_one",
        suffixes=("", "_repay"),
    )

    dup_pd_post = df_pd_out.duplicated(
        subset=["agent_msisdn", "snapshot_dt"], keep=False
    ).sum()
    assert int(dup_pd_post) == 0, (
        "[run_phase_2_2] PD duplicated after merge — merge keys not unique"
    )

    # ------------------------------------------------------------------ #
    # Recompute labels now that penalty columns exist
    # ------------------------------------------------------------------ #
    if "bad_state_30D" in df_pd_out.columns or "bad_state" in df_pd_out.columns:
        df_pd_out = compute_bad_flags(df_pd_out)

    # ------------------------------------------------------------------ #
    # Schema guards
    # ------------------------------------------------------------------ #
    missing_required = [
        c for c in ["agent_msisdn", "snapshot_dt"] if c not in df_pd_out.columns
    ]
    assert not missing_required, (
        f"[run_phase_2_2] Columns lost during repayment merge: {missing_required}"
    )
    assert pd.api.types.is_datetime64_any_dtype(df_pd_out["snapshot_dt"]), (
        "[run_phase_2_2] snapshot_dt corrupted during repayment merge"
    )
    if "bad_state" in df_pd_out.columns:
        assert "bad_state" in df_pd_out.columns, (
            "[run_phase_2_2] bad_state missing after compute_bad_flags"
        )

    # ------------------------------------------------------------------ #
    # Thin-file guardrail
    # ------------------------------------------------------------------ #
    repayment_behavioural_features = [
        c for c in repayment_numeric_features if c in df_pd_out.columns
    ]
    assert repayment_behavioural_features, (
        "[run_phase_2_2] No repayment features available for thin-file guardrail"
    )

    df_pd_out[repayment_behavioural_features] = (
        df_pd_out[repayment_behavioural_features]
        .apply(pd.to_numeric, errors="coerce")
        .replace([np.inf, -np.inf], np.nan)
    )

    if "thin_file_flag" not in df_pd_out.columns:
        df_pd_out["thin_file_flag"] = 0
    if "thin_file_pd_prior" not in df_pd_out.columns:
        df_pd_out["thin_file_pd_prior"] = df_pd_out["thin_file_flag"]

    df_pd_out["thin_file_flag"] = df_pd_out["thin_file_flag"].fillna(0).astype(int)

    missing_mask = df_pd_out[repayment_behavioural_features].isna().all(axis=1)
    df_pd_out["thin_file_flag"] = (
        df_pd_out["thin_file_flag"] | missing_mask.astype(int)
    ).astype(int)

    thin_mask = df_pd_out["thin_file_flag"] == 1
    df_pd_out.loc[thin_mask, repayment_behavioural_features] = np.nan

    failed_cols = (
        df_pd_out.loc[thin_mask, repayment_behavioural_features]
        .columns[~df_pd_out.loc[thin_mask, repayment_behavioural_features].isna().all()]
        .tolist()
    )
    if failed_cols:
        raise AssertionError(
            f"[run_phase_2_2] Thin-file nullification failed for columns: {failed_cols}"
        )

    assert (
        df_pd_out.loc[thin_mask, repayment_behavioural_features].isna().all().all()
    ), "[run_phase_2_2] Leakage risk: repayment behaviour present for thin-file agents"

    # ------------------------------------------------------------------ #
    # Date integrity guard
    # ------------------------------------------------------------------ #
    for c in df_pd_out.columns:
        if "date" not in c.lower() and not c.lower().endswith("_dt"):
            continue
        ser = df_pd_out[c]
        if pd.api.types.is_datetime64_any_dtype(ser):
            continue
        parsed = pd.to_datetime(ser, errors="coerce")
        if ser.notna().any() and parsed.notna().sum() == 0:
            raise AssertionError(
                f"[run_phase_2_2] Column '{c}' is not parseable as datetime"
            )
        if parsed.notna().sum() > 0:
            df_pd_out[c] = parsed

    if verbose:
        logger.info(
            "run_phase_2_2: added %d repayment behavioural features; "
            "thin-file agents: %d",
            len(repayment_behavioural_features),
            int(df_pd_out["thin_file_flag"].fillna(0).astype(int).sum()),
        )

    return df_pd_out, df_repayments_out
